version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 80

  tests:
    build: .
    command: pytest -q
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - web
